DROP TABLE agentii CASCADE CONSTRAINTS;
DROP TABLE astronauti CASCADE CONSTRAINTS;
DROP TABLE cataloage CASCADE CONSTRAINTS;
DROP TABLE locatii CASCADE CONSTRAINTS;
DROP TABLE misiuni CASCADE CONSTRAINTS;
DROP TABLE tehnicieni CASCADE CONSTRAINTS;
	