-- Generated by Oracle SQL Developer Data Modeler 20.2.0.167.1538
--   at:        2020-11-30 23:06:38 EET
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE agentii (
    acronim_agentie  VARCHAR2(10) NOT NULL,
    nume_agentie     VARCHAR2(64) NOT NULL,
    fonduri          INTEGER NOT NULL
);

ALTER TABLE agentii
    ADD CONSTRAINT agentii_acronim_ck CHECK ( length(acronim_agentie) > 2 );

ALTER TABLE agentii ADD CONSTRAINT agentii_pk PRIMARY KEY ( acronim_agentie );

CREATE TABLE astronauti (
    id_astronaut            INTEGER NOT NULL,
    nume_astronaut          VARCHAR2(32) NOT NULL,
    masa                    NUMBER(5, 2) NOT NULL,
    inaltime                INTEGER NOT NULL,
    varsta                  INTEGER NOT NULL,
    specializare_astronaut  VARCHAR2(32),
    id_misiune              INTEGER NOT NULL,
    acronim_agentie         VARCHAR2(10) NOT NULL
);

ALTER TABLE astronauti ADD CONSTRAINT astronauti_masa_ck CHECK ( masa > 60 );

ALTER TABLE astronauti ADD CONSTRAINT astronauti_inaltime_ck CHECK ( inaltime >= 150 );

ALTER TABLE astronauti ADD CONSTRAINT astronauti_varsta_ck CHECK ( varsta > 18 );

ALTER TABLE astronauti
    ADD CONSTRAINT astronauti_pk PRIMARY KEY ( id_astronaut,
                                               id_misiune,
                                               acronim_agentie );

CREATE TABLE cataloage (
    abreviere_catalog  VARCHAR2(16) NOT NULL,
    nume_catalog       VARCHAR2(64) NOT NULL,
    detalii            VARCHAR2(70)
);

ALTER TABLE cataloage ADD CONSTRAINT cataloage_pk PRIMARY KEY ( abreviere_catalog );

CREATE TABLE locatii (
    id_locatie         INTEGER NOT NULL,
    nume_locatie       VARCHAR2(128) NOT NULL,
    abreviere_catalog  VARCHAR2(16) NOT NULL
);

ALTER TABLE locatii ADD CONSTRAINT locatii_pk PRIMARY KEY ( id_locatie );

CREATE TABLE misiuni (
    id_misiune        INTEGER NOT NULL,
    nume_misiune      VARCHAR2(64) NOT NULL,
    data_inceperii    DATE NOT NULL,
    deadline_lansare  DATE,
    id_locatie        INTEGER NOT NULL
);

CREATE UNIQUE INDEX misiuni__idx ON
    misiuni (
        id_locatie
    ASC );

ALTER TABLE misiuni ADD CONSTRAINT misiuni_pk PRIMARY KEY ( id_misiune );

CREATE TABLE tehnicieni (
    id_tehnician            INTEGER NOT NULL,
    nume_tehnician          VARCHAR2(32) NOT NULL,
    specializare_tehnician  VARCHAR2(32),
    id_misiune              INTEGER NOT NULL,
    acronim_agentie         VARCHAR2(10) NOT NULL
);

ALTER TABLE tehnicieni
    ADD CONSTRAINT tehnicieni_pk PRIMARY KEY ( id_tehnician,
                                               id_misiune,
                                               acronim_agentie );

ALTER TABLE astronauti
    ADD CONSTRAINT agentii_astronauti_fk FOREIGN KEY ( acronim_agentie )
        REFERENCES agentii ( acronim_agentie );

ALTER TABLE tehnicieni
    ADD CONSTRAINT agentii_astronauti_fkv2 FOREIGN KEY ( acronim_agentie )
        REFERENCES agentii ( acronim_agentie );

ALTER TABLE locatii
    ADD CONSTRAINT cataloage_locatii_fk FOREIGN KEY ( abreviere_catalog )
        REFERENCES cataloage ( abreviere_catalog );

ALTER TABLE misiuni
    ADD CONSTRAINT locatii_misiuni_fk FOREIGN KEY ( id_locatie )
        REFERENCES locatii ( id_locatie );

ALTER TABLE astronauti
    ADD CONSTRAINT misiuni_astronauti_fk FOREIGN KEY ( id_misiune )
        REFERENCES misiuni ( id_misiune );

ALTER TABLE tehnicieni
    ADD CONSTRAINT misiuni_tehnicieni_fk FOREIGN KEY ( id_misiune )
        REFERENCES misiuni ( id_misiune );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             6
-- CREATE INDEX                             1
-- ALTER TABLE                             16
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
